object Versions {
   val infinispanVersion = "9.4.1.Final"
   val protoStreamVersion = "4.2.2.Final"
   val sparkVersion = "2.4.4"
   val scalaTestVersion = "2.2.5"
   val junitVersion = "4.11"
   val twitter4jVersion = "4.0.4"
   val jcipAnnotationsVersion = "1.0"
   val scalaDMRVersion = "0.2.0"
   val shrinkWrapVersion = "1.2.3"
   val log4jVersion = "1.2.14"
   val sl4jVersion = "1.7.21"
   val twitterHbcVersion = "2.2.0"
   val playJsonVersion = "2.5.4"
   val uJsonVersion = "0.6.6"
}
