object Versions {
   val infinispanVersion = "10.0.1.Final"
   val protoStreamVersion = "4.3.0.Final"
   val nettyVersion = "4.1.43.Final"
   val sparkVersion = "2.4.4"
   val scalaTestVersion = "3.0.8"
   val junitVersion = "4.11"
   val twitter4jVersion = "4.0.4"
   val jcipAnnotationsVersion = "1.0"
   val shrinkWrapVersion = "1.2.3"
   val log4jVersion = "1.2.14"
   val sl4jVersion = "1.7.21"
   val twitterHbcVersion = "2.2.0"
   val playJsonVersion = "2.6.0"
   val uJsonVersion = "0.6.6"
   val sttpVersion = "2.0.0-M7"
}
